<br />
<b>Fatal error</b>:  Uncaught exception 'Zend\View\Exception\RuntimeException' with message 'No RouteMatch instance provided' in /home/cenarioc/vendor/zendframework/zendframework/library/Zend/View/Helper/Url.php:64
Stack trace:
#0 [internal function]: Zend\View\Helper\Url-&gt;__invoke()
#1 /home/cenarioc/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php(393): call_user_func_array(Object(Zend\View\Helper\Url), Array)
#2 /home/cenarioc/module/Cron/view/layout/layout.phtml(47): Zend\View\Renderer\PhpRenderer-&gt;__call('url', Array)
#3 /home/cenarioc/module/Cron/view/layout/layout.phtml(47): Zend\View\Renderer\PhpRenderer-&gt;url()
#4 /home/cenarioc/vendor/zendframework/zendframework/library/Zend/View/Renderer/PhpRenderer.php(501): include('/home/cenarioc/...')
#5 /home/cenarioc/vendor/zendframework/zendframework/library/Zend/View/View.php(205): Zend\View\Renderer\PhpRenderer-&gt;render(Object(Zend\View\Model\ViewModel))
#6 /home/cenarioc/vendor/zendframework/zendframework/library/Zend/Mvc/View/Http/DefaultRenderingS in <b>/home/cenarioc/vendor/zendframework/zendframework/library/Zend/View/Helper/Url.php</b> on line <b>64</b><br />
